version: '3'
services:
  server:
    image: badconfig/lib-misis
    container_name: server
    tty: true
    environment:
      - DATABASE_URL=postgres://main:NavwNgTnxyWsz7hy5yRmEKC4X@misis-lib_postgres:5432/diesel_db
    ports:
      - "8088:8088"
    volumes:
      - ./migrations/:/misis-lib/migrations/
    networks:
      - app-network
  postgres:
    image: "postgres:12.6"
    container_name: misis-lib_postgres
    restart: unless-stopped
    ports:
      - "7089:5432"
    environment:
      POSTGRES_DB: diesel_db
      POSTGRES_PASSWORD: NavwNgTnxyWsz7hy5yRmEKC4X
      POSTGRES_USER: main
    networks:
      - app-network
    volumes:
      - pg_misis-lib:/var/lib/postgresql/data
volumes:
  pg_misis-lib:
networks:
  app-network:
    driver: bridge
